# Generated by Django 4.2.27 on 2026-02-18 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvitoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Дайте понятное имя (например, 'Рабочий', 'Личный')", max_length=100, verbose_name='Название аккаунта')),
                ('avito_client_id', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Avito Client ID')),
                ('avito_client_secret', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Avito Client Secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Аккаунт Avito',
                'verbose_name_plural': 'Аккаунты Avito',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BiddingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField(verbose_name='ID объявления Avito')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название объявления')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL картинки')),
                ('search_url', models.URLField(max_length=1000, verbose_name='URL для поиска')),
                ('min_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Мин. цена')),
                ('max_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Макс. цена')),
                ('bid_step', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Шаг ставки (₽)')),
                ('target_position_min', models.PositiveIntegerField(default=1, verbose_name='Целевая позиция (от)')),
                ('target_position_max', models.PositiveIntegerField(default=10, verbose_name='Целевая позиция (до)')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Дневный лимит трат (₽, 0 = без лимита)')),
                ('freeze_price_if_not_found', models.BooleanField(default=False, help_text='В случае если объявление окажется ниже 50-го места, то стоимость просмотра НЕ БУДЕТ ПОВЫШАТЬСЯ (чаще всего актуально в нишах, где используется массовый постинг)', verbose_name='Выход из 50-го места')),
                ('current_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущая позиция в выдаче')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущая ставка')),
                ('schedule', models.TextField(blank=True, default='[]', verbose_name='Расписание (JSON-строка)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('avito_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main_app.avitoaccount', verbose_name='Аккаунт Avito')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание для биддера',
                'verbose_name_plural': 'Задания для биддера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='INFO', max_length=10)),
                ('message', models.TextField(verbose_name='Сообщение лога')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main_app.biddingtask')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Записи логов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
