# Generated by Django 4.2.27 on 2026-01-30 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField(verbose_name='ID объявления Avito')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название объявления')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL картинки')),
                ('search_url', models.URLField(max_length=1000, verbose_name='URL для поиска')),
                ('min_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Мин. цена')),
                ('max_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Макс. цена')),
                ('bid_step', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Шаг ставки (₽)')),
                ('target_position', models.PositiveIntegerField(default=10, verbose_name='Целевая позиция (до)')),
                ('schedule', models.TextField(blank=True, default='[]', verbose_name='Расписание (JSON-строка)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание для биддера',
                'verbose_name_plural': 'Задания для биддера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avito_client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Avito Client ID')),
                ('avito_client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Avito Client Secret')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='INFO', max_length=10)),
                ('message', models.TextField(verbose_name='Сообщение лога')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main_app.biddingtask')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Записи логов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
