# Generated by Django 4.2.27 on 2026-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingtask',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск'),
        ),
    ]
