# Generated by Django 4.2.27 on 2026-02-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingtask',
            name='freeze_price_if_not_found',
            field=models.BooleanField(default=False, help_text='В случае если объявление окажется ниже 50-го места, то стоимость просмотра НЕ БУДЕТ ПОВЫШАТЬСЯ (чаще всего актуально в нишах, где используется массовый постинг)', verbose_name='Выход из 50-го места'),
        ),
    ]
