# Generated by Django 4.2.27 on 2026-01-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biddingtask',
            old_name='target_position',
            new_name='target_position_max',
        ),
        migrations.AddField(
            model_name='biddingtask',
            name='target_position_min',
            field=models.PositiveIntegerField(default=1, verbose_name='Целевая позиция (от)'),
        ),
    ]
