# Generated by Django 4.2.27 on 2026-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingtask',
            name='current_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущая позиция в выдаче'),
        ),
        migrations.AddField(
            model_name='biddingtask',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущая ставка'),
        ),
    ]
