# Generated by Django 4.2.27 on 2026-02-16 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_biddingtask_freeze_price_if_not_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avito_client_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avito_client_secret',
        ),
        migrations.AlterField(
            model_name='biddingtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='AvitoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Дайте понятное имя (например, 'Рабочий', 'Личный')", max_length=100, verbose_name='Название аккаунта')),
                ('avito_client_id', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Avito Client ID')),
                ('avito_client_secret', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Avito Client Secret')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avito_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Аккаунт Avito',
                'verbose_name_plural': 'Аккаунты Avito',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='biddingtask',
            name='avito_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main_app.avitoaccount', verbose_name='Аккаунт Avito'),
        ),
    ]
