# Generated by Django 4.2.27 on 2026-02-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_biddingtask_last_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingtask',
            name='last_run',
        ),
    ]
