# Generated by Django 4.2.27 on 2026-02-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_userprofile_avito_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingtask',
            name='daily_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Дневный лимит трат (₽, 0 = без лимита)'),
        ),
    ]
