# Generated by Django 4.2.27 on 2026-01-16 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.BigIntegerField(verbose_name='ID объявления Avito')),
                ('search_url', models.URLField(max_length=1000, verbose_name='URL для поиска')),
                ('min_price', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Мин. цена')),
                ('max_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Макс. цена')),
                ('target_position', models.PositiveIntegerField(default=10, verbose_name='Целевая позиция (до)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задание для биддера',
                'verbose_name_plural': 'Задания для биддера',
                'ordering': ['-created_at'],
            },
        ),
    ]
