# Generated by Django 4.2.27 on 2026-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avito_profile_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Профиля Avito'),
        ),
    ]
